### ISSUE TITLE
cort-predict-raw cannot run on all specific raw text

### ISSUE THREAD

**Issue by bennytieu** [smartschat/cort#16]
I'm trying to run cort-predict-raw OOTB using the following setup: 
```
cort-predict-raw -in ~/data/test1/*.txt \
		-model models/model-pair-train.obj \
		-extractor cort.coreference.approaches.mention_ranking.extract_substructures \
		-perceptron cort.coreference.approaches.mention_ranking.RankingPerceptron \
		-clusterer cort.coreference.clusterer.all_ante \
		-corenlp ~/systems/stanford/stanford-corenlp-full-2016-10-31 \
		#-features my_features.txt \
```
For some reason it throws an exception for the string "SEC" (with quotations) in: 

> Hello my name is "SEC".

If I replace SEC or remove the quotations the file will pass through.

The exception: 
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/cort-predict-raw", line 136, in <module>
    doc.system_mentions = mention_extractor.extract_system_mentions(doc)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/cort/core/mention_extractor.py", line 36, in extract_system_mentions
    for span in __extract_system_mention_spans(document)]
  File "/home/ubuntu/.local/lib/python3.5/site-packages/cort/core/mention_extractor.py", line 36, in <listcomp>
    for span in __extract_system_mention_spans(document)]
  File "/home/ubuntu/.local/lib/python3.5/site-packages/cort/core/mentions.py", line 153, in from_document
    mention_property_computer.compute_head_information(attributes)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/cort/core/mention_property_computer.py", line 248, in compute_head_information
    attributes["ner"][head_index])
  File "/home/ubuntu/.local/lib/python3.5/site-packages/cort/core/head_finders.py", line 214, in adjust_head_for_nam
    raise Exception("Unknown named entity annotation: " + ner_type)
Exception: Unknown named entity annotation: DURATION
```

**Comment by smartschat** [comment]
This issue was brought up in #6 and resolved in the meantime. If you update to the recent version of cort there should be no exception anymore.

**Comment by bennytieu** [comment]
I've tried to update to the latest version through cort through pip and pip3, and also use the latest commit in the master branch, same problem. Where is the most recent version?

**Comment by smartschat** [comment]
Ah, I did not upload the most recent version to PyPi. I just did that now, could you try to upgrade again? (It was already fixed in the master branch, maybe your environment tried to access the installed version of cort.)

**Comment by bennytieu** [comment]
Yes, my mistake, I ran it with the environment variables (PyPi), It works now after your update. Thank you!
