### ISSUE TITLE
CoreNLP error

### ISSUE THREAD

**Issue by yuliagrishina** [smartschat/cort#2]
hi! I get an error from CoreNLP when I'm trying to predict coreference on raw text using "cort-predict-raw" and standard parameters as described in the manual. this is what I get:

2015-11-05 10:37:23,639 INFO Loading model.
2015-11-05 10:37:55,518 INFO Reading in and preprocessing data.
2015-11-05 10:37:55,519 INFO Starting java subprocess, and waiting for signal it's ready, with command: exec java -Xmx4g -XX:ParallelGCThreads=1 -cp '/Library/Python/2.7/site-packages/stanford_corenlp_pywrapper/lib/_:/Users/yuliagrishina/Documents/Software/CoreNLP_'      corenlp.SocketServer --outpipe /tmp/corenlp_pywrap_pipe_pypid=2721_time=1446716275.52  --configfile /Library/Python/2.7/site-packages/cort/config_files/corenlp.ini
INFO:CoreNLP_JavaServer: Using CoreNLP configuration file: /Library/Python/2.7/site-packages/cort/config_files/corenlp.ini
Exception in thread "main" java.lang.NoClassDefFoundError: edu/stanford/nlp/pipeline/StanfordCoreNLP
    at corenlp.JsonPipeline.initializeCorenlpPipeline(JsonPipeline.java:206)
    at corenlp.SocketServer.main(SocketServer.java:102)
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 2 more

do you have any idea why this happens?

**Comment by smartschat** [comment]
Which operating system do you use?

**Comment by yuliagrishina** [comment]
i'm using MacOS 10.10.5

**Comment by smartschat** [comment]
I've developed and tested cort only under Linux. Unfortunately, I do not have any Mac available. Can you run [Stanford CoreNLP Pywrapper](https://github.com/brendano/stanford_corenlp_pywrapper) as standalone?

**Comment by yuliagrishina** [comment]
Pywrapper throws the same error :(
so it's seems that something's wrong with it, not with cort. thanks anyway for pointing that out!

**Comment by smartschat** [comment]
According to Pywrapper's readme, it should work under Mac. Maybe you can open an issue there? 

I'm closing this issue.
