### ISSUE TITLE
"KeyError: None" while training

### ISSUE THREAD

**Issue by minhlab** [smartschat/cort#23]
I'm trying to train a model derived from CoNLL-2012 training set when I got this error.

This is the details of the model:
`('-extractor', 'cort.coreference.approaches.mention_ranking.extract_substructures', '-perceptron', 'cort.coreference.approaches.mention_ranking.RankingPerceptron', '-cost_function', 'cort.coreference.cost_functions.cost_based_on_consistency', '-cost_scaling', '100')`

This is the error:

```
    2018-09-10 19:57:49,116 INFO Started epoch 1
    Traceback (most recent call last):
    File "output/cort/venv/bin/cort-train", line 4, in <module>
        __import__('pkg_resources').run_script('cort==0.2.4.5', 'cort-train')
    File "/Users/minh/EvEn/output/cort/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
        self.require(requires)[0].run_script(script_name, ns)
    File "/Users/minh/EvEn/output/cort/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
        exec(code, namespace, namespace)
    File "/Users/minh/EvEn/output/cort/venv/lib/python3.7/site-packages/cort-0.2.4.5-py3.7.egg/EGG-INFO/scripts/cort-train", line 141, in <module>
        perceptron
    File "/Users/minh/EvEn/output/cort/venv/lib/python3.7/site-packages/cort-0.2.4.5-py3.7.egg/cort/coreference/experiments.py", line 43, in learn
        perceptron.fit(substructures, arc_information)
    File "output/cort/venv/lib/python3.7/site-packages/cort-0.2.4.5-py3.7.egg/cort/coreference/perceptrons.pyx", line 182, in cort.coreference.perceptrons.Perceptron.fit
        self.__update(cons_arcs,
    File "output/cort/venv/lib/python3.7/site-packages/cort-0.2.4.5-py3.7.egg/cort/coreference/perceptrons.pyx", line 331, in cort.coreference.perceptrons.Perceptron.__update
        arc_information[arc][0]
    KeyError: None
```

Could you please have a look?

**Comment by smartschat** [comment]
Are you using the standard CoNLL-2012 training set and the standard mention extraction? 

It would be very helpful to know for which document this error happens. Could you modify cort to print/log this information (for example by adding `print(cons_arcs)` to line 174 of perceptrons.pyx)?

**Comment by minhlab** [comment]
Sorry, I meant training a model on a dataset derived from CoNLL-2012. I was trying to test some hypotheses by running models on slightly different datasets. I will try to print out more information in next days.

**Comment by minhlab** [comment]
Please ignore this, it is a bug that I accidentally created while studying the code.
